# Generated by Django 3.2.2 on 2023-10-23 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_commerce', '0003_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('marvel_id', models.PositiveIntegerField(unique=True, verbose_name='marvel id')),
                ('favorite', models.BooleanField(default=1, verbose_name='favorite')),
                ('cart', models.BooleanField(default=1, verbose_name='cart')),
                ('wished_qty', models.PositiveIntegerField(default=1, verbose_name='whished_qty')),
                ('bought_qty', models.PositiveIntegerField(default=1, verbose_name='bought_qty')),
                ('comic', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commerce.comic', verbose_name='Comic')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comic')),
            ],
            options={
                'verbose_name': 'wish_list',
                'verbose_name_plural': 'wish_list',
                'db_table': 'e_commerce_wish_list',
            },
        ),
    ]
