# Generated by Django 3.2.2 on 2023-10-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_auto_20231024_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='marvel_id',
        ),
    ]
